import Head from 'next/head'
import Background from '../components/bg'
import Link from 'next/link'

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Vivek Mahendra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-screen flex flex-col'>
        <nav className='h-[100px] bg-black text-white p-4'>
          <div className='flex justify-between p-6 px-8 w-full'>
            <div className='text-6xl font-barcode'>Vivek Mahendra</div>
            <div className='font-mono text-lg md:flex space-x-8 hidden'>
              <div><Link href="/about">About</Link></div>
              <div>Blog</div>
              <div>Projects</div>
              <div>Photos</div>
            </div>
          </div>
        </nav>
        <main className='flex-1 p-4 bg-black'>
            <Background />
        </main>
        <footer className='h-[80px] bg-black p-4 text-white'>
          <div className='flex justify-center'>
            Made in PHX 🌵
          </div>
        </footer>
      </div>
    </>
  )
}

