import Head from 'next/head'
import Background from '../components/bg'

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Vivek Mahendra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className='bg-black h-[80px] p-6 px-8 flex justify-between text-white '>
        <div className='text-2xl'>Vivek Mahendra</div>
        <div className='font-mono text-lg flex space-x-8'>
          <div>About</div>
          <div>Blog</div>
          <div>Projects</div>
          <div>Photos</div>
          <div>Contact</div>
        </div>
      </nav>
      <main className='h-screen bg-black'>
        <div className='absolute top-0 w-screen z-10 text-white'>
          <div>

          </div>
        </div>
        <div className='h-full'>
          <Background />
        </div>
      </main>
      <footer className='absolute bottom-8 text-white font-thin w-full'>
        <div className='flex justify-center'>
          Made in PHX 🌵
        </div>
      </footer>
    </>
  )
}

